---
  name: Dynamic

  on:
    push:
      # Validate: all branches
      # Apply: master
      paths:
        - "dynamic/**"
        - "**"
    workflow_dispatch:

  env:
    # testing!
    ENVIRONMENT_NAME: "IND_WEU_DEV"
    WORKING_DIR: "dynamic/" 

  jobs:
    validate_terraform:
      name: Terraform
      ## no latest!!!
      runs-on: ubuntu-latest

      steps:

        - name: 'Checkout Repo'
          uses: actions/checkout@v2.3.1
          with:
            # get all commits -- diff among pushes to master
            fetch-depth: 0

        # Environment by branch
        - name: 'Select environment'
          id: environment 
          run: |
            env |grep ENV
            # env -- branch
            # branch=${GITHUB_REF##*/} 
            # echo "::set-output name=ENVIRONMENT::${branch^^}"
            echo "::set-output name=ENVIRONMENT::${ENV}"
          env:
            ENV: ${env.ENVIRONMENT_NAME}
        # Get dynamic environment
        - name: 'Get secrets Environment'
          run: |
            env |grep ENV
            ls -l
            # 1 
            echo "SECRET TO FILE:"
            cat <<EOF >>landing.json
            ${{ env.ENVIRONMENT_NAME }}
            EOF
            # jq . landing.json
            jq . secrets.json
            # alternative
            echo "ENVIROMENT VARIABLE:"
            echo "${ENVIRONMENT}" > landing2.json
            ls -l
          working-directory: ${{ env.WORKING_DIR }}
          env:
            #ENVIRONMENT: ${{ secrets[steps.environment.outputs.ENVIRONMENT] }}
            ENVIRONMENT: ${{ secrets[env.ENVIRONMENT_NAME] }}
          