---
  name: Dynamic Workflow

  on:
    push:
      # Validate: all branches
      # Apply: master
      paths:
        - "dynamic/**"
    workflow_dispatch:

  env:
    # testing!
    ENVIRONMENT_NAME: "IND_WEU_DEV"

  jobs:
    validate_terraform:
      name: Terraform
      ## no latest!!!
      runs-on: ubuntu-latest

      steps:

        - name: 'Checkout Repo'
          uses: actions/checkout@v2.3.1
          with:
            # get all commits -- diff among pushes to master
            fetch-depth: 0

        # Get dynamic environment
        - name: 'Get secrets Environment'
          run: |
            printf "" "$AZURE_IND_WEU_DEV"
            
          working-directory: ${{ env.TF_WORKING_DIR}}
          env:
            AZURE_DEV : ${{ secrets.AZURE_IND_WEU_DEV }}
