---
  name: Dynamic

  on:
    push:
      # Validate: all branches
      # Apply: master
      paths:
        - "dynamic/**"
        - "**"
    workflow_dispatch:

  env:
    # testing!
    ENVIRONMENT_NAME: "IND_WEU_DEV"
    WORKING_DIR: "dynamic/" 

  jobs:
    validate_terraform:
      name: Terraform
      ## no latest!!!
      runs-on: ubuntu-latest

      steps:

        - name: 'Checkout Repo'
          uses: actions/checkout@v2.3.1
          with:
            # get all commits -- diff among pushes to master
            fetch-depth: 0

        # Environment by branch
        - name: 'Select environment'
          id: selectenv 
          run: |
            env |grep ENV
            # env -- branch
            # branch=${GITHUB_REF##*/} 
            # echo "::set-output name=ENVIRONMENT_SELECTED::${branch^^}"
            echo "::set-output name=ENVIRONMENT_SELECTED::${ENV}"
          env:
            ENV: ${env.ENVIRONMENT_NAME}

        # Get dynamic environment
        - name: 'Get secrets Environment'
          run: |
            docker images
            env |grep ENV
            ls -l

            # 1 way ***************************************
            echo "SECRET TO FILE:"
            cat <<EOF >>landing1.json
            ${{ secrets[env.ENVIRONMENT_NAME] }}
            EOF

            # alternative *********************************
            echo "ENVIROMENT VARIABLE:"
            echo "${ENVIRONMENT}" > landing2.json

            # check
            ls -l
            md5sum secrets.json
            md5sum landing1.json
            md5sum landing2.json

            jq .tf_backend secrets.json > tf_backend_secrets.json
            jq .tf_backend landing1.json > tf_backend_landing1.json
            md5sum tf_backend_secrets.json
            md5sum tf_backend_landing1.json
             

          working-directory: ${{ env.WORKING_DIR }}
          env:
            #ENVIRONMENT: ${{ secrets[steps.selectenv.outputs.ENVIRONMENT_SELECTED] }}
            ENVIRONMENT: ${{ secrets[env.ENVIRONMENT_NAME] }}
          
